[versions]
minecraft = "1.19.4"
quilt_mappings = "1.19.4+build.1"

fabric_loom = "1.3.8"
fabric_loader = "0.14.22"

modmenu = "6.1.0"
fabric_api = "0.75.3+1.19.4"

cloth_config = "10.0.96"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }

fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

cloth_config = { module = "me.shedaniel.cloth:cloth-config-fabric", version.ref = "cloth_config" }

[bundles]
fabric_api = ["fabric_api"]

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "fabric_loom" }
